# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b53be03996023553a054bfba65c0c3b45438612f16d06dea8429e374bba2526201ea650312d0e23fc090ae98548d698d1de3f0a2f2a66d10e2bcf0377add844f

test:
  secret_key_base: 04c81091bd6de1430acf76af5132121198f2d21a79e57315a3439a6f808274f4ec5f2f4c67a5a62bca70333fc9eca55a72e8650d13dcb4039f126880d8b68915

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
